package ru.stepanov.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ru.stepanov.database.entity.DbAppointment;
import ru.stepanov.database.entity.DictionaryCutServices;

/**
 * Class _DbAppointmentServices was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbAppointmentServices extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<DbAppointment> APPOINTMENT_SERVICES_TO_APPOINTMENT = Property.create("appointmentServicesToAppointment", DbAppointment.class);
    public static final Property<DictionaryCutServices> APPOINTMENT_SERVICES_TO_SERVICES = Property.create("appointmentServicesToServices", DictionaryCutServices.class);

    public void setAppointmentServicesToAppointment(DbAppointment appointmentServicesToAppointment) {
        setToOneTarget("appointmentServicesToAppointment", appointmentServicesToAppointment, true);
    }

    public DbAppointment getAppointmentServicesToAppointment() {
        return (DbAppointment)readProperty("appointmentServicesToAppointment");
    }


    public void setAppointmentServicesToServices(DictionaryCutServices appointmentServicesToServices) {
        setToOneTarget("appointmentServicesToServices", appointmentServicesToServices, true);
    }

    public DictionaryCutServices getAppointmentServicesToServices() {
        return (DictionaryCutServices)readProperty("appointmentServicesToServices");
    }


}
