package ru.stepanov.database.entity.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ru.stepanov.database.entity.DbAppointment;

/**
 * Class _DbAddress was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbAddress extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> APARTMENT = Property.create("apartment", String.class);
    public static final Property<String> CITY = Property.create("city", String.class);
    public static final Property<String> COORDINATES = Property.create("coordinates", String.class);
    public static final Property<String> COUNTRY = Property.create("country", String.class);
    public static final Property<String> HOUSE = Property.create("house", String.class);
    public static final Property<String> REGION = Property.create("region", String.class);
    public static final Property<String> STREET = Property.create("street", String.class);
    public static final Property<List<DbAppointment>> ADDRESS_TO_APPOINTMENT = Property.create("addressToAppointment", List.class);

    public void setApartment(String apartment) {
        writeProperty("apartment", apartment);
    }
    public String getApartment() {
        return (String)readProperty("apartment");
    }

    public void setCity(String city) {
        writeProperty("city", city);
    }
    public String getCity() {
        return (String)readProperty("city");
    }

    public void setCoordinates(String coordinates) {
        writeProperty("coordinates", coordinates);
    }
    public String getCoordinates() {
        return (String)readProperty("coordinates");
    }

    public void setCountry(String country) {
        writeProperty("country", country);
    }
    public String getCountry() {
        return (String)readProperty("country");
    }

    public void setHouse(String house) {
        writeProperty("house", house);
    }
    public String getHouse() {
        return (String)readProperty("house");
    }

    public void setRegion(String region) {
        writeProperty("region", region);
    }
    public String getRegion() {
        return (String)readProperty("region");
    }

    public void setStreet(String street) {
        writeProperty("street", street);
    }
    public String getStreet() {
        return (String)readProperty("street");
    }

    public void addToAddressToAppointment(DbAppointment obj) {
        addToManyTarget("addressToAppointment", obj, true);
    }
    public void removeFromAddressToAppointment(DbAppointment obj) {
        removeToManyTarget("addressToAppointment", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbAppointment> getAddressToAppointment() {
        return (List<DbAppointment>)readProperty("addressToAppointment");
    }


}
