package ru.stepanov.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ru.stepanov.database.entity.DictionaryCutServices;

/**
 * Class _DbCutterServices was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbCutterServices extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<DictionaryCutServices> CUTTER_SERVICES_TO_SERVICES = Property.create("cutterServicesToServices", DictionaryCutServices.class);

    public void setCutterServicesToServices(DictionaryCutServices cutterServicesToServices) {
        setToOneTarget("cutterServicesToServices", cutterServicesToServices, true);
    }

    public DictionaryCutServices getCutterServicesToServices() {
        return (DictionaryCutServices)readProperty("cutterServicesToServices");
    }


}
