package ru.stepanov.database.entity.auto;

import java.time.LocalDateTime;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ru.stepanov.database.entity.DbAttachment;
import ru.stepanov.database.entity.DbChat;

/**
 * Class _DbMessage was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DbMessage extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDateTime> CREATED_DATE = Property.create("createdDate", LocalDateTime.class);
    public static final Property<LocalDateTime> DELETED_DATE = Property.create("deletedDate", LocalDateTime.class);
    public static final Property<Boolean> HAS_ATTACHMENT = Property.create("hasAttachment", Boolean.class);
    public static final Property<LocalDateTime> MODIFIED_DATE = Property.create("modifiedDate", LocalDateTime.class);
    public static final Property<String> TEXT = Property.create("text", String.class);
    public static final Property<List<DbAttachment>> MESSAGE_TO_ATTACHMENT = Property.create("messageToAttachment", List.class);
    public static final Property<DbChat> MESSAGE_TO_CHAT = Property.create("messageToChat", DbChat.class);

    public void setCreatedDate(LocalDateTime createdDate) {
        writeProperty("createdDate", createdDate);
    }
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime)readProperty("createdDate");
    }

    public void setDeletedDate(LocalDateTime deletedDate) {
        writeProperty("deletedDate", deletedDate);
    }
    public LocalDateTime getDeletedDate() {
        return (LocalDateTime)readProperty("deletedDate");
    }

    public void setHasAttachment(boolean hasAttachment) {
        writeProperty("hasAttachment", hasAttachment);
    }
	public boolean isHasAttachment() {
        Boolean value = (Boolean)readProperty("hasAttachment");
        return (value != null) ? value.booleanValue() : false;
    }

    public void setModifiedDate(LocalDateTime modifiedDate) {
        writeProperty("modifiedDate", modifiedDate);
    }
    public LocalDateTime getModifiedDate() {
        return (LocalDateTime)readProperty("modifiedDate");
    }

    public void setText(String text) {
        writeProperty("text", text);
    }
    public String getText() {
        return (String)readProperty("text");
    }

    public void addToMessageToAttachment(DbAttachment obj) {
        addToManyTarget("messageToAttachment", obj, true);
    }
    public void removeFromMessageToAttachment(DbAttachment obj) {
        removeToManyTarget("messageToAttachment", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbAttachment> getMessageToAttachment() {
        return (List<DbAttachment>)readProperty("messageToAttachment");
    }


    public void setMessageToChat(DbChat messageToChat) {
        setToOneTarget("messageToChat", messageToChat, true);
    }

    public DbChat getMessageToChat() {
        return (DbChat)readProperty("messageToChat");
    }


}
