package ru.stepanov.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _DictionaryEmailTemplate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DictionaryEmailTemplate extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> TEMPLATE = Property.create("template", String.class);
    public static final Property<String> TITLE = Property.create("title", String.class);

    public void setTemplate(String template) {
        writeProperty("template", template);
    }
    public String getTemplate() {
        return (String)readProperty("template");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

}
