package ru.stepanov.database.entity.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _DictionaryGender was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DictionaryGender extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> GENDER = Property.create("gender", String.class);

    public void setGender(String gender) {
        writeProperty("gender", gender);
    }
    public String getGender() {
        return (String)readProperty("gender");
    }

}
