package ru.stepanov.database.entity.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import ru.stepanov.database.entity.DbAppointmentServices;
import ru.stepanov.database.entity.DbCutterServices;

/**
 * Class _DictionaryCutServices was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DictionaryCutServices extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<Integer> DURATION_MIN = Property.create("durationMin", Integer.class);
    public static final Property<String> TITLE = Property.create("title", String.class);
    public static final Property<List<DbAppointmentServices>> SERVICES_TO_APPOINTMENT_SERVICES = Property.create("servicesToAppointmentServices", List.class);
    public static final Property<List<DbCutterServices>> SERVICES_TO_CUTTERS_SERVICES = Property.create("servicesToCuttersServices", List.class);

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setDurationMin(int durationMin) {
        writeProperty("durationMin", durationMin);
    }
    public int getDurationMin() {
        Object value = readProperty("durationMin");
        return (value != null) ? (Integer) value : 0;
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void addToServicesToAppointmentServices(DbAppointmentServices obj) {
        addToManyTarget("servicesToAppointmentServices", obj, true);
    }
    public void removeFromServicesToAppointmentServices(DbAppointmentServices obj) {
        removeToManyTarget("servicesToAppointmentServices", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbAppointmentServices> getServicesToAppointmentServices() {
        return (List<DbAppointmentServices>)readProperty("servicesToAppointmentServices");
    }


    public void addToServicesToCuttersServices(DbCutterServices obj) {
        addToManyTarget("servicesToCuttersServices", obj, true);
    }
    public void removeFromServicesToCuttersServices(DbCutterServices obj) {
        removeToManyTarget("servicesToCuttersServices", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<DbCutterServices> getServicesToCuttersServices() {
        return (List<DbCutterServices>)readProperty("servicesToCuttersServices");
    }


}
